adding project initilization workflow

diff --git a/.github/workflows/init-project.yml b/.github/workflows/init-project.yml
--- a/.github/workflows/init-project.yml
+++ b/.github/workflows/init-project.yml
@@ -1,56 +1,62 @@
 
-    name: Deployed to Section
+FROM node:18-alpine AS base
 
-    on:
-      push:
-        branches: [main, create-project-webhook]
-      workflow_dispatch:
-    
-    env:
-      REGISTRY: ghcr.io
-      REPO:  ${{ github.repository }}
-    
-    jobs:
-      build-push:
-        runs-on: ubuntu-latest
-        permissions:
-          contents: read
-          packages: write
-    
-        steps:
-          - name: Checkout
-            uses: actions/checkout@v3
-    
-          - name: Log in to the Container registry
-            uses: docker/login-action@v2
-            with:
-              registry: ${{ env.REGISTRY }}
-              username: ${{ github.actor }}
-              password: ${{ secrets.GITHUB_TOKEN }}
-    
-          - name: downcase REPO
-            run: |
-              echo "IMAGE_NAME=${REPO,,}" >>${GITHUB_ENV}
-    
-          - name: Extract metadata (tags, labels) for Docker
-            id: meta
-            uses: docker/metadata-action@v4
-            with:
-              images:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-    
-          - name: Build and push Docker image
-            uses: docker/build-push-action@v3
-            with:
-              context: .
-              push: true
-              tags: ${{ steps.meta.outputs.tags }}
-              labels: ${{ steps.meta.outputs.labels }}
-    
-          - name: Deploy on Section
-            env:
-              SECTION_K8S_API_URL: '${{ secrets.SECTION_K8S_API_URL }}'
-              SECTION_API_TOKEN: '${{ secrets.SECTION_API_TOKEN }}'
-              GHCR_TOKEN: '${{ secrets.GHCR_TOKEN }}' 
-              DEBUG: 1
-            run: |
-              ./ci/deploy.sh main
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile;   else echo "Lockfile not found." && exit 1;   fi
+
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+RUN mkdir -p public
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN   if [ -f yarn.lock ]; then yarn run build;   elif [ -f package-lock.json ]; then npm run build;   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build;   else echo "Lockfile not found." && exit 1;   fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/public ./public
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+# Set the correct permission for prerender cache
+RUN mkdir -p .next/cache
+RUN chown -R nextjs:nodejs .next
+RUN chmod -R 777 .next/cache
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD ["node", "server.js"]
